"""
AI Trading Analyst
===================
Uses Claude (claude-sonnet-4-6) to analyse market data and approve/reject
trade signals generated by the RSI+MA strategy.

Called by bot.py before every buy or sell. Returns a decision dict:
  {
    "decision":   "BUY" | "SELL" | "HOLD",
    "confidence": 0-100,
    "reason":     "short explanation",
    "approved":   True | False
  }
"""

import json
import logging
import requests
import config
from news_aggregator import get_news_summary

log = logging.getLogger(__name__)

ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
GROK_API_URL      = "https://api.x.ai/v1/chat/completions"
MODEL_CLAUDE      = "claude-sonnet-4-6"
MODEL_GROK        = "grok-3"

def analyse(symbol, action, price, rsi, ma, candles, rsi_signal, mode):
    """Route to fake AI (paper, free), Claude, or Grok based on config."""
    if config.PAPER_TRADING:
        import fake_ai
        result = fake_ai.analyse(symbol, action, price, rsi, ma, candles, rsi_signal, mode)
        log.info(f"[FAKE AI] {symbol} {action} → {result['decision']} {result['confidence']}% | {result['reason']}")
        return result
    provider = getattr(config, "AI_PROVIDER", "claude").lower()
    if provider == "grok":
        return _grok_analyse(symbol, action, price, rsi, ma, candles, rsi_signal, mode)
    return _real_analyse(symbol, action, price, rsi, ma, candles, rsi_signal, mode)




# ══════════════════════════════════════════════════════════════════════════════
#  NEWS SEARCH (optional — called before AI analysis if AI_NEWS_SEARCH=True)
# ══════════════════════════════════════════════════════════════════════════════

def fetch_news_headlines(coin: str) -> str:
    """
    Uses Claude's web_search tool to get recent headlines for the coin.
    Returns a short string of bullet-point headlines, or empty string on failure.
    """
    try:
        payload = {
            "model": MODEL,
            "max_tokens": 500,
            "tools": [{"type": "web_search_20250305", "name": "web_search"}],
            "messages": [{
                "role": "user",
                "content": (
                    f"Search for the 5 most recent news headlines about {coin} cryptocurrency "
                    f"from the last 24 hours. Return ONLY a plain bullet list of headlines, "
                    f"no extra commentary. If nothing found, return 'No recent news found.'"
                )
            }]
        }
        resp = requests.post(
            ANTHROPIC_API_URL,
            headers={
                "x-api-key":         config.AI_API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type":      "application/json",
            },
            json=payload,
            timeout=30,
        )
        if resp.ok:
            data     = resp.json()
            texts    = [b["text"] for b in data.get("content", []) if b.get("type") == "text"]
            headline = "\n".join(texts).strip()
            return headline if headline else "No recent news found."
        else:
            log.warning(f"[AI NEWS] Request failed: {resp.status_code}")
            return "News search unavailable."
    except Exception as e:
        log.warning(f"[AI NEWS] Error: {e}")
        return "News search unavailable."


# ══════════════════════════════════════════════════════════════════════════════
#  MAIN AI ANALYSIS
# ══════════════════════════════════════════════════════════════════════════════

def _real_analyse(
    symbol:       str,
    action:       str,
    price:        float,
    rsi:          float,
    ma:           float,
    candles:      list,
    rsi_signal:   bool,
    mode:         str,
) -> dict:
    """Ask Claude to analyse the trade signal using live news from 5 sources."""
    if not config.AI_ENABLED:
        return {"decision": action, "confidence": 100, "reason": "AI disabled", "approved": True}

    coin = symbol.split("-")[0]

    # ── Fetch live news from all 5 sources ─────────────────────────────────
    news_section = ""
    if config.AI_NEWS_SEARCH:
        log.info(f"[AI] Fetching news for {coin} from 5 sources...")
        news_section = get_news_summary(coin)

    # ── Build candle summary ────────────────────────────────────────────────
    candle_str   = ", ".join([f"${c:.4f}" for c in candles[-10:]])
    price_change = ((candles[-1] - candles[-5]) / candles[-5] * 100) if len(candles) >= 5 else 0

    # ── Trend direction ────────────────────────────────────────────────────
    trend = "UPTREND" if candles[-1] > candles[-5] else "DOWNTREND" if candles[-1] < candles[-5] else "SIDEWAYS"

    rsi_ma_line = (
        f"RSI+MA strategy has triggered a {action} signal."
        if rsi_signal else
        f"No RSI+MA signal — AI making an independent decision."
    )

    prompt = f"""You are an expert cryptocurrency trading analyst with access to live market news.
Analyse this trade signal using both technical data and current news sentiment.

═══ TECHNICAL DATA ═══
COIN:              {coin} ({symbol})
ACTION:            {action}
PRICE:             ${price:,.6f}
RSI ({config.RSI_PERIOD}-period):    {rsi}  (Buy < {config.RSI_BUY} | Sell > {config.RSI_SELL})
MA  ({config.MA_PERIOD}-period):    ${ma:,.6f}
PRICE vs MA:       {'ABOVE' if price > ma else 'BELOW'} moving average
TREND (5 candles): {trend} ({price_change:+.2f}%)
LAST 10 CANDLES:   {candle_str}
SIGNAL SOURCE:     {rsi_ma_line}

═══ TRADE CONTEXT ═══
- Short-term bot, 15-minute candles
- Trade size: small (~$5-10 USDT)
- Goal: avoid false signals in choppy markets
- Goal: catch genuine momentum moves with news confirmation
{news_section}

═══ YOUR TASK ═══
Consider BOTH the technical signals AND the news sentiment above.
- If news is bearish for this coin → be more conservative on BUY signals
- If news is bullish → be more confident on BUY signals
- If major negative event (hack, regulatory ban, exchange issue) → HOLD regardless
- Weight recent news from The Block and CoinDesk heavily (most reliable)

Respond ONLY with JSON — no markdown, no extra text:
{{
  "decision": "{action}" or "HOLD",
  "confidence": <integer 0-100>,
  "reason": "<max 20 words explaining technical + news factors>",
  "news_sentiment": "bullish" or "bearish" or "neutral" or "unknown"
}}

Rules:
- "decision" must be "{action}" or "HOLD" only
- Confidence >= {config.AI_CONFIDENCE_MIN} = approve the trade
- Be conservative — if news conflicts with technicals, lean toward HOLD
"""

    # ── Call Claude API ─────────────────────────────────────────────────────
    try:
        resp = requests.post(
            ANTHROPIC_API_URL,
            headers={
                "x-api-key":         config.AI_API_KEY,
                "anthropic-version": "2023-06-01",
                "content-type":      "application/json",
            },
            json={
                "model":      MODEL_CLAUDE,
                "max_tokens": 250,
                "messages":   [{"role": "user", "content": prompt}],
            },
            timeout=30,
        )

        if not resp.ok:
            log.warning(f"[AI] API error {resp.status_code}: {resp.text[:200]}")
            return _fallback(action, "API error — defaulting to RSI+MA signal")

        data     = resp.json()
        raw_text = "".join(b.get("text", "") for b in data.get("content", []) if b.get("type") == "text")
        raw_text = raw_text.strip().lstrip("```json").lstrip("```").rstrip("```").strip()

        result = json.loads(raw_text)

        decision       = result.get("decision", "HOLD").upper()
        confidence     = int(result.get("confidence", 0))
        reason         = result.get("reason", "")
        news_sentiment = result.get("news_sentiment", "unknown")
        approved       = (decision == action) and (confidence >= config.AI_CONFIDENCE_MIN)

        log.info(f"[AI {coin}] {action} → {decision} | {confidence}% | news:{news_sentiment} | {reason}")
        return {
            "decision":       decision,
            "confidence":     confidence,
            "reason":         reason,
            "news_sentiment": news_sentiment,
            "approved":       approved,
        }

    except json.JSONDecodeError as e:
        log.warning(f"[AI] JSON parse error: {e} | Raw: {raw_text[:100]}")
        return _fallback(action, "JSON parse error — defaulting to RSI+MA signal")
    except Exception as e:
        log.warning(f"[AI] Unexpected error: {e}")
        return _fallback(action, f"Error: {e}")


def _fallback(action: str, reason: str) -> dict:
    """If AI call fails, approve the trade so RSI+MA still works."""
    log.warning(f"[AI] Fallback triggered: {reason}")
    return {"decision": action, "confidence": 100, "reason": reason, "approved": True}


def _grok_analyse(symbol, action, price, rsi, ma, candles, rsi_signal, mode):
    # Call xAI Grok API for trading decision
    coin = symbol.split("-")[0]
    candle_str   = ", ".join([f"${c:.4f}" for c in candles[-10:]])
    price_change = ((candles[-1]-candles[-5])/candles[-5]*100) if len(candles)>=5 else 0

    prompt = (
        f"You are an expert crypto trading analyst. Analyse this signal and decide.\n"
        f"COIN: {coin} | ACTION: {action} | PRICE: ${price:,.4f}\n"
        f"RSI({config.RSI_PERIOD}): {rsi} | MA({config.MA_PERIOD}): ${ma:,.4f}\n"
        f"Last 10 candles: {candle_str}\n"
        f"Price change (5 candles): {price_change:+.2f}%\n\n"
        f"Respond ONLY with JSON (no markdown):\n"
        f'{{ "decision": "{action}" or "HOLD", "confidence": 0-100, "reason": "max 20 words" }}\n'
        f"Confidence >= {config.AI_CONFIDENCE_MIN} = approve. Be conservative — if unsure, HOLD."
    )

    try:
        resp = requests.post(
            GROK_API_URL,
            headers={
                "Authorization": f"Bearer {config.GROK_API_KEY}",
                "Content-Type":  "application/json",
            },
            json={
                "model":    MODEL_GROK,
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 150,
            },
            timeout=30,
        )
        if not resp.ok:
            log.warning(f"[GROK] API error {resp.status_code}")
            return _fallback(action, "Grok API error")

        raw_text = resp.json()["choices"][0]["message"]["content"].strip()
        raw_text = raw_text.replace("```json","").replace("```","").strip()
        result   = json.loads(raw_text)

        decision   = result.get("decision", "HOLD").upper()
        confidence = int(result.get("confidence", 0))
        reason     = result.get("reason", "")
        approved   = (decision == action) and (confidence >= config.AI_CONFIDENCE_MIN)

        log.info(f"[GROK {coin}] {action} → {decision} | {confidence}% | {reason}")
        return {"decision": decision, "confidence": confidence, "reason": reason, "approved": approved}

    except Exception as e:
        log.warning(f"[GROK] Error: {e}")
        return _fallback(action, f"Grok error: {e}")
